<?php

namespace Rasadent\Common\PageBuilder\Enums;

enum PageBuilderComponentTypeEnum: string
{
    case HERO_SLIDER = 'HERO_SLIDER';
    case CATEGORIES_GRID = 'CATEGORIES_GRID';
    case DISCOUNTS_CAROUSEL = 'DISCOUNTS_CAROUSEL';
    case NEWEST_PRODUCTS = 'NEWEST_PRODUCTS';
    case PROMOTED_PRODUCTS = 'PROMOTED_PRODUCTS';
    case HALF_WIDTH_BANNER = 'HALF_WIDTH_BANNER';
    case HALF_WIDTH_BANNER_2 = 'HALF_WIDTH_BANNER_2';
    case QUARTER_BANNER = 'QUARTER_BANNER';
    case FULL_WIDTH_BANNER = 'FULL_WIDTH_BANNER';
    case BLOG_GRID = 'BLOG_GRID';
    case SINGLE_CATEGORY_CAROUSEL = 'SINGLE_CATEGORY_CAROUSEL';
    case SINGLE_BRAND_CAROUSEL = 'SINGLE_BRAND_CAROUSEL';
    case SINGLE_BLOG_CATEGORY_CAROUSEL = 'SINGLE_BLOG_CATEGORY_CAROUSEL';
    case SINGLE_SHOP_CAROUSEL = 'SINGLE_SHOP_CAROUSEL';
    case BEST_SELLER_CAROUSEL = 'BEST_SELLER_CAROUSEL';
    case VENDORS_CAROUSEL = 'VENDORS_CAROUSEL';
    case TESTIMONIALS = 'TESTIMONIALS';
    case BRANDS_GRID = 'BRANDS_GRID';
    case SEO_BOX = 'SEO_BOX';
    case FAQ = 'FAQ';
}
