<?php

namespace Rasadent\Common\Permission\Enums;

enum PermissionEnum: string
{
    case ADMIN_PANEL = 'ADMIN_PANEL';

    case MANAGE_ORDERS = 'MANAGE_ORDERS';
    case MANAGE_PRODUCTS = 'MANAGE_PRODUCTS';
    case MANAGE_STOCKS = 'MANAGE_STOCKS';
    case MANAGE_CATEGORIES = 'MANAGE_CATEGORIES';
    case MANAGE_USERS = 'MANAGE_USERS';
    case MANAGE_SHOPS = 'MANAGE_SHOPS';
    case MANAGE_ARTICLES = 'MANAGE_ARTICLES';
    case MANAGE_BRANDS = 'MANAGE_BRANDS';
    case MANAGE_CREDITS = 'MANAGE_CREDITS';
    case MANAGE_CATALOGS = 'MANAGE_CATALOGS';
    case MANAGE_TICKETS = 'MANAGE_TICKETS';
    case MANAGE_OFFERS = 'MANAGE_OFFERS';
    case MANAGE_DISCOUNTS = 'MANAGE_DISCOUNTS';
    case MANAGE_PROMOTIONS = 'MANAGE_PROMOTIONS';
    case MANAGE_TESTIMONIALS = 'MANAGE_TESTIMONIALS';
    case MANAGE_PERMISSIONS = 'MANAGE_PERMISSIONS';
    case MANAGE_TEAM = 'MANAGE_TEAM';
    case MANAGE_ERROR_REPORTS = 'MANAGE_ERROR_REPORTS';
    case MANAGE_SETTINGS = 'MANAGE_SETTINGS';
    case MANAGE_NOTIFICATIONS = 'MANAGE_NOTIFICATIONS';
    case SUPERADMIN = 'SUPERADMIN';
}
