<?php

namespace Rasadent\Common\Notification\Enums;

enum NotifiactionEventKey: string {
    case OTP = 'otp';
    
    case ADMIN_NEW_CREDIT_REQUEST = 'ADMIN_NEW_CREDIT_REQUEST';
    case ADMIN_NEW_TICKET = 'ADMIN_NEW_TICKET';
    case ADMIN_NEW_PRODUCT_REQUEST = 'ADMIN_NEW_PRODUCT_REQUEST';
    case ADMIN_NEW_CHORTKEH_LICENSE_PURCHASE = 'ADMIN_NEW_CHORTKEH_LICENSE_PURCHASE';
    case ADMIN_NEW_INVOICE = 'ADMIN_NEW_INVOICE';
    case ADMIN_PRODUCT_SENT_FROM_SHOP_TO_RASADENT = 'ADMIN_PRODUCT_SENT_FROM_SHOP_TO_RASADENT';
    case ADMIN_SHOP_REJECT_ORDER_ITEM = 'ADMIN_SHOP_REJECT_ORDER_ITEM';

    case SHOP_NEW_INVOICE = 'SHOP_NEW_INVOICE';

    case CLIENT_PRODUCT_RESTOCKED = 'CLIENT_PRODUCT_RESTOCKED';
    case CLIENT_CHORTKEH_LICENSE_PURCHASED = 'CLIENT_CHORTKEH_LICENSE_PURCHASED';
    case CLIENT_TICKET_ANSWERED = 'CLIENT_TICKET_ANSWERED';
    case CLIENT_WALLET_DEPOSIT = 'CLIENT_WALLET_DEPOSIT';
    case CLIENT_WALLET_WITHDRAW = 'CLIENT_WALLET_WITHDRAW';
    case CLIENT_INVOICE_STATUS_CHANGE = 'CLIENT_INVOICE_STATUS_CHANGE';
    case CLIENT_INVOICE_ACCEPT = 'CLIENT_INVOICE_ACCEPT';
}
